### ISSUE TITLE
Due righe in più nel README.md

### ISSUE THREAD

**Issue by aborruso** [andriaz/parco_circolante_srd#1]
Caro @andriaz rompo le scatole solo perché mi piacciono le cose che fai.

Senza fretta e impegno, scriverei nel README qual'era l'obiettivo dello script.

Grazie

**Comment by andriaz** [comment]
Ciao @aborruso ! si, ora mi ci metto. L'ho fatto al volo di notte giusto per metterlo da parte e lavorarci meglio

**Comment by andriaz** [comment]
done
